/*
 * This Java source file was generated by the Gradle 'init' task.
 */


package Assignment2;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.*;
import java.io.*;

public class AppTest {
    @Test public void testBookOne () {

      String type = "book";
      String productID = "123456";
      String description = "math book";
      String price = "100.56";
      int year = 2008;
      String authors = "Yaser";
      String publisher = "Habibi";

      Product bookTest = new Product(productID, description, price, year, authors, publisher);

      assertEquals( productID, bookTest.getProductID());
      assertEquals( description, bookTest.getDescription());
      assertEquals( price, bookTest.getPrice());
      assertEquals( year, bookTest.getYear());
      assertEquals( authors, bookTest.getAuthors());
      assertEquals( publisher, bookTest.getPublisher());
    }

    @Test public void testBookTwo () {

      String productID = "122122";
      String description = "c textbook for programming";
      String price = "30.45";
      int year = 2030;
      String authors = "Fei";
      String publisher = "Song";

      Product bookTest = new Product(productID, description, price, year, authors, publisher);

      assertEquals( productID, bookTest.getProductID());
      assertEquals( description, bookTest.getDescription());
      assertEquals( price, bookTest.getPrice());
      assertEquals( year, bookTest.getYear());
      assertEquals( authors, bookTest.getAuthors());
      assertEquals( publisher, bookTest.getPublisher());
    }

    @Test public void testElectronicOne () {

      String productID = "091256";
      String description = "c# programming";
      String price = "699.45";
      int year = 2045;
      String maker = "Fei Song";

      Product electronicsTest = new Product (productID, description, price, year, maker);

      assertEquals( productID, electronicsTest.getProductID());
      assertEquals( description, electronicsTest.getDescription());
      assertEquals( price, electronicsTest.getPrice());
      assertEquals( year, electronicsTest.getYear());
      assertEquals( maker, electronicsTest.getMaker());
    }

    @Test public void testElectronicClassTwo () {

      String productID = "006578";
      String description = "";
      String price = "";
      int year = 2041;
      String maker = "Albert Einstein Inc";

      Product electronicsTest = new Product (productID, description, price, year, maker);

      assertEquals( productID, electronicsTest.getProductID());
      assertEquals( description, electronicsTest.getDescription());
      assertEquals( price, electronicsTest.getPrice());
      assertEquals( year, electronicsTest.getYear());
      assertEquals( maker, electronicsTest.getMaker());
    }

    @Test public void testProductOne () {

      String productID = "456456";
      String description = "programming is fun";
      String price = "122.45";
      int year = 2003;

      Product productTest = new Product (productID, description, price, year);

      assertEquals( productID, productTest.getProductID());
      assertEquals( description, productTest.getDescription());
      assertEquals( price, productTest.getPrice());
    }

    @Test public void testProductTwo () {

      String productID = "000900";
      String description = "pysics textbook on gravity";
      String price = "500.34";
      int year = 2045;

      Product productTest = new Product (productID, description, price, year);

      assertEquals( productID, productTest.getProductID());
      assertEquals( description, productTest.getDescription());
      assertEquals( price, productTest.getPrice());
      assertEquals( year, productTest.getYear());
    }
}
